// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB4Uxb4KnFRZMWhqLmlvkQ6fZ6U_cuEDkQ',
    appId: '1:1015467968719:web:767435017601df202dcfba',
    messagingSenderId: '1015467968719',
    projectId: 'chat-app-344f7',
    authDomain: 'chat-app-344f7.firebaseapp.com',
    storageBucket: 'chat-app-344f7.appspot.com',
    measurementId: 'G-GT703614NP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBkwYhj9rPJeSD46nTDdIkPK-b4QzLjZ3E',
    appId: '1:1015467968719:android:bfc2b65e0e6824af2dcfba',
    messagingSenderId: '1015467968719',
    projectId: 'chat-app-344f7',
    storageBucket: 'chat-app-344f7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDuKcvEhcRFgoagehOPaxbGLw-2kbvFIZw',
    appId: '1:1015467968719:ios:196dca3a0dcecee22dcfba',
    messagingSenderId: '1015467968719',
    projectId: 'chat-app-344f7',
    storageBucket: 'chat-app-344f7.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );
}
